global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'currency-exchange-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['currency-exchange-service:8081']
        labels:
          application: 'Currency Exchange Service Application'
  - job_name: 'currency-conversion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['currency-conversion-service:8082']
        labels:
          application: 'Currency Conversion Service Application'