{
 "title": "Spring Boot Applications Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Currency Exchange Service - Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Currency Exchange Service Application\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Currency Conversion Service - Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Currency Conversion Service Application\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Currency Exchange Service - JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"Currency Exchange Service Application\",area=\"heap\"}",
     "legendFormat": "{{area}} - Heap"
    }
   ]
  },
  {
   "title": "Currency Conversion Service - JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"Currency Conversion Service Application\",area=\"heap\"}",
     "legendFormat": "{{area}} - Heap"
    }
   ]
  }
 ]
}